#!/bin/bash

#pass1=$(command -v python3.9)
#pass2=$(command -v python39)
#echo $pass1
#echo $pass2

#p3version=$(python3 --version | awk '{print $2}' | awk 'BEGIN {FS="."}; {if ($1 == 3) {if ($2 >= 9) {print "Y";} else {print "N";}} else {print "N";}}'i)

#p2version=$(python --version | awk '{print $2}' | awk 'BEGIN {FS="."}; {if ($1 == 3) {if ($2 >= 9) {print "Y";} else {print "N";}} else {print "N";}}'i)

#echo $version

#apt-get install python3.9
#apt-get install git

#t1=$(which python3) 
#if [[ $t1 == "" ]]
#then echo "No"
#fi

echo "Версии ПО на этом компьютере:"
echo $(python3 --version)
echo $(pip --version)
echo $(pip3 --version)
echo $(git --version)

